services:
  tmx-wng:
    container_name: ${PROJECT_NAME:-tmx-wng}-c
    build: .
    image: tmwd/${PROJECT_NAME:-tmx-wng}:${PROJECT_VERSION:-latest}
    ports:
      - 3000:3000
    volumes:
      - .:/${PROJECT_NAME:-tmx-wng}
